name = "saas-backend"
main = "src/index.ts"
compatibility_date = "2024-03-01"

kv_namespaces = [
  { binding = "RATE_LIMIT_KV", id = "RATE_LIMIT_KV" }
]

r2_buckets = [
  { binding = "USER_UPLOADS", bucket_name = "user-uploads" }
]

[vars]
DATABASE_URL = "${DATABASE_URL}"
CLERK_SECRET_KEY = "${CLERK_SECRET_KEY}"
STRIPE_SECRET_KEY = "${STRIPE_SECRET_KEY}"
R2_PUBLIC_DOMAIN = "your-public.r2.dev" 